### ISSUE TITLE
The url of the code is a 404 page

### ISSUE THREAD

**Issue by Juzhan** [CRLab/reachabilityawaregrasping#1]
In index.md, some webpage links such as: [http://github.com/CRLab/reachability_space_generation.git](http://github.com/CRLab/reachability_space_generation.git) has expired.
I want to run these code and learn how to achieve "Online Grasp Planning" 😃.
![image](https://user-images.githubusercontent.com/18376468/44341027-506c9b00-a4b9-11e8-9930-2f0e4cfefb2e.png)

**Comment by iretiayo** [comment]
Thanks for point this out. The broken webpage links should be fixed now.
